### PR TITLE
Noindex pdfjs html pages

### PR DESCRIPTION
**Pull request by evannoronha**
This pull modifies the viewer.html source for pdfjs and commits the resulting build.

CC @sctice

### CODE REVIEW

**Comment by djmetzle** [comment]
CR :question:

**Comment by sctice** [comment]
It doesn't look like this includes the built `viewer.html`. Am I missing something?

**Comment by evannoronha** [comment]
You're not missing anything! I committed directly to master in the previous change to `build/viewer.html` so there wasn't any change to commit in this pull.

**Comment by sctice** [comment]
Ahah, got it. Thanks!

**Pull request merged**
